import { Inter } from "next/font/google";
import Head from 'next/head'

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Deno Next Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      {/* <link type="image/png" sizes="96x96" rel="icon" href="./favicon.png"/> */}
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
